Migrate Next 14 To Next 15 (#10)
* fix: Enhance ProfileHeader loading friends state with Skeleton component

* refactor: Add jenkinsfile

* feat: Enhance profile components with editable state and loading indicators

* feat: Implement advanced filtering options for books by author, series, and rating

* feat: Add filtering options for activities and users based on status, author, series, and rating

* refactor: separate bookRating in a diferents componentes

* refactor: simplify BookRating component by removing unused variables and improving code clarity

* fix: ensure isBookSaved is a boolean in BookRating component

* refactor: update next.js to v15 and fix project configuration

* fix: rename jest config to use cjs extension

* refactor: update Auth0 mock and jest configuration for improved testing

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,12 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+echo "🎨 Formatting and linting staged files..."
 npx lint-staged
+
+if [ $? -ne 0 ]; then
+  echo "❌ Formatting or linting failed! Commit aborted."
+  exit 1
+fi
+
+echo "✅ Files formatted and linted successfully!"
